// Generated by extendr
// This calls the Rust-generated init function

#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

// Rust entry point generated by extendr
void R_init_ferx_extendr(DllInfo *dll);

void R_init_ferx(DllInfo *dll) {
    R_init_ferx_extendr(dll);
}
