# Generated by extendr: Do not edit by hand

# nolint start

#' @docType package
#' @usage NULL
#' @useDynLib ferx, .registration = TRUE
NULL

#' @export
ferx_rust_fit <- function(model_path, data_path, method, maxiter, covariance, verbose) {
  .Call("wrap__ferx_rust_fit", model_path, data_path, method, maxiter, covariance, verbose)
}

#' @export
ferx_rust_simulate <- function(model_path, data_path, n_sim, seed) {
  .Call("wrap__ferx_rust_simulate", model_path, data_path, n_sim, seed)
}

#' @export
ferx_rust_predict <- function(model_path, data_path) {
  .Call("wrap__ferx_rust_predict", model_path, data_path)
}

# nolint end
