# Generated by extendr: Do not edit by hand

# nolint start

# Note: the `@docType package` / `@useDynLib` preamble that rextendr < 0.4
# emitted here has been removed — `@useDynLib` now lives in R/ferx-package.R
# alongside the `"_PACKAGE"` sentinel. When regenerating this file with
# rextendr >= 0.4, the preamble will not be re-emitted. With an older
# rextendr it will be re-added; delete the block again (or upgrade rextendr).

#' @export
ferx_rust_fit <- function(model_path, data_path, method, maxiter, covariance, verbose, bloq_method, threads, mu_referencing, sir, settings_keys, settings_values) {
  .Call("wrap__ferx_rust_fit", model_path, data_path, as.character(method), maxiter, covariance, verbose, bloq_method, threads, mu_referencing, sir, as.character(settings_keys), as.character(settings_values))
}

#' @export
ferx_rust_simulate <- function(model_path, data_path, n_sim, seed) {
  .Call("wrap__ferx_rust_simulate", model_path, data_path, n_sim, seed)
}

#' @export
ferx_rust_simulate_from_fit <- function(model_path, data_path, theta, omega_flat, omega_dim, sigma, n_sim, seed) {
  .Call("wrap__ferx_rust_simulate_from_fit", model_path, data_path, theta, omega_flat, omega_dim, sigma, n_sim, seed)
}

#' @export
ferx_rust_predict <- function(model_path, data_path) {
  .Call("wrap__ferx_rust_predict", model_path, data_path)
}

#' @export
ferx_rust_predict_from_fit <- function(model_path, data_path, theta, omega_flat, omega_dim, sigma) {
  .Call("wrap__ferx_rust_predict_from_fit", model_path, data_path, theta, omega_flat, omega_dim, sigma)
}

# nolint end
